name: Deploy to VPS

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        THREAD_ID: ${{ secrets.THREAD_ID }}
        OWNER_ID: ${{ secrets.OWNER_ID }}
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        envs: BOT_TOKEN,GROUP_ID,THREAD_ID,OWNER_ID
        script_path: scripts/deploy.sh
